### PR TITLE
Add support for Samsung DeX mode desktop mouse(touchpad) events

### LINKED ISSUE #1029: Galaxy Tab S7 with Keyboard Cover mouse not working
**Describe the bug**
On a Samsung Galaxy Tab S7 with keyboard cover, the trackpad isn't moving the mouse. I can click the trackpad and it works as expected, and actually if I move the cursor with the trackpad before I click it, it moves to where I moved it too. I am not convinced it is moving it before hand though, as I can't seem to see any hover animations or anything on Windows. Also, touchscreen mouse control works as expected

**Steps to reproduce**
Use Moonlight with Keyboard Cover

**Screenshots**
N/A

**Affected games**
N/A

**Other Moonlight clients**
- Does the issue occur when using Moonlight on PC or iOS?
Android

**Moonlight settings (please complete the following information)**
- No

**Gamepad-related issues (please complete if problem is gamepad-related)**
- No

**Device details (please complete the following information)**
 - Android version: [e.g. Android 10] Android 11
 - Device model: [e.g. Samsung Galaxy S21] Samsung Galaxy Tab S7

**Server PC details (please complete the following information)**
 N/A

**Additional context**
Anything else you think may be relevant to the issue or special about your specific setup.

### PR DESCRIPTION
**Pull request by himekifee**
This should fix #1029. Inspiration from [awtk-android](https://github.com/zlgopen/awtk-android/blob/6a73b3b901bbef1096b57a1e935f377daa43b096/android-project/app/src/main/java/org/libsdl/app/SDLActivity.java#L1699).

### CODE REVIEW

**Comment by himekifee** [comment]
It kinda works but the cursor disappears after a few secs like a stylus. Should we put it here or add `MotionEvent.ACTION_HOVER_ENTER` etc to the lower fingers case part? Since the logic of 3 finger gesture is down there and the touchpad supports 3 fingers, I feel it should be there. Sorry for my naive understanding of the code.

**Comment by cgutman** [comment]
Can explain in more detail how the touchpad behaves? Is it acting like a `SOURCE_TOUCHPAD` device and sending us events for individual fingers?

FWIW, when using DeX on my Galaxy Note 9, it seems to work fine without any changes. Maybe that's because it's an older Android version.

**Comment by himekifee** [comment]
I've recorded a [video](https://nextcloud.himeki.net/index.php/s/4f5ep2A5Woo2P3C) clip to show the behaviour. Please let me know if anything is not clear enough. Those events do not support double fingers well. The primary target would probably be getting one finger work. However Android's `getevent` actually shows proper events for multiple fingers and I can confirm the source code has three fingers support.

**Comment by himekifee** [comment]
Any update to this?

**Comment by cgutman** [comment]
Sorry, I'm still not quite clear on whether this PR resolves the issue or not. It sounds like you think further modifications are needed?

It looks like the video link expired too.

**Comment by himekifee** [comment]
Yup, I'm not sure if this one should be processed in the tooltip type finger or not. [Here](https://nextcloud.himeki.net/index.php/s/jpd5yCTGdfmRFr6) is the new link.

**Comment by cgutman** [comment]
Interesting. When you got those `ACTION_DOWN` and `ACTION_MOVE` events were you performing a click and drag? If so, are you just getting `ACTION_HOVER_MOVE` when you move the mouse without clicking?

**Comment by himekifee** [comment]
Yup, but that's when the finger surfer on the pad. If finger down and wait a bit, there will be an `ACTION_HOVER_EXIT` and then `ACTION_DOWN` then the events become `ACTION_MOVE` instead of  `ACTION_HOVER_MOVE`.

**Pull request merged**
