### PR TITLE
New Touch Analog Stick Implementation

### PR DESCRIPTION
**Pull request by lucasassislar**
Hello, I was testing out Moonlight this week (mostly comparing it to Steam Link and seeing what are the advantages/disavantages), one thing that bothered me was the touch analog stick being fixed was really hard to use.
So I decided to fork the project and implement a stick like most analog in Android games/the way it works in Steam Link:
GTA V with the new analog: https://www.youtube.com/watch?v=4BG2t5v1gHI
How it works: If the user isn't pressing the analog stick, the first touch that actually does press is saved (and the touch id is saved too). Now the analog is relative to the start touch point, instead of being fixed on-screen. The setup changes to be a squared area where the analog works, not the entire analog area.
BTW sorry if the code is not as clean as possible, I'm a C# developer (I tinker with Java from time to time but compared to C# I actually have no experience whatsoever), I tried making it as clean as I knew how to.
Screenshot_20200220-193552_Moonlight (Debug)
Screenshot_20200220-191321_Moonlight (Debug)
Screenshot_20200220-191305_Moonlight (Debug)

### CODE REVIEW

**Comment by 8116453** [comment]
I really like the scheme you designed, but I want to ask you a question: how to operate the R3 and L3 keys? Can I add them to the existing scheme?

**Comment by 8116453** [comment]
Can you send me the app and help me test it? Thank you very much. My email :8116453@qq.com

**Comment by thw0rted** [comment]
I like the idea of this mode though I haven't had a chance to test this implementation yet.  I'd like to suggest a few things:

* L3/R3 when you double tap in the region, not sure if there's already code to detect a double-tap but should be simple enough to register
* Settings toggle between the current (release) behavior and this behavior, for those that like the old way.
* Maybe the default control layout when in this mode should have separate L3/R3 onscreen buttons?

**Comment by lucasassislar** [comment]
Yeah its already working by double tap, I didn't change the original implementation.
I tested it on Borderlands 2 and it was working great, you double tap and then push the analog to the top and the character runs fine. Only weird thing is that sometimes you double tap without really noticing (I crouched a few times by double tapping the right side of the screen when I wanted to move the camera). It might work to have a toggle between double-tap and on-screen L3 and R3, but that could clunk the screen a bit.
Can I just post a download link to my Drive? https://drive.google.com/open?id=1CJlGGrKbz3tO10RIEbdSw1348VEkbwL6

**Comment by 8116453** [comment]
The use effect is really not much. If you can do some beautification in the UI, it will be better (for example, you can add a pointed scissor). Thank you for your development, which is really great.

**Comment by 8116453** [comment]
Hello, respectable programmer: I found a problem with button combination. When I press the "RB" key and then click the "A B X Y" key to combine with them, they will take effect, but when I press the "RT" key and click the "A B X Y" key, they will not take effect at the same time). This is very useful in some games, such as ACU, which requires the combination of "RT" and "A" key to jump. But I have to press them with two fingers, which is uncomfortable. If I can press the "RT" key and stroke the "A" key at the same time, they can work at the same time, which will be very convenient. I hope you can fix this problem.
My English is not very good. I hope you can understand it.

**Comment by lucasassislar** [comment]
Oh okay! English is not my native language either so were kinda in the same boat :P
I'll check that issue out, today or tomorrow I'll push a new commit

**Comment by 8116453** [comment]
When I press "RT" and the fingers slide to the "A B X Y" key without leaving the screen, they will work together. Thank you for fixing this

**Comment by 8116453** [comment]
Dear programmers, have you made any progress in this project?

**Comment by cgutman** [comment]
I agree with @thw0rted that we should have a toggle for this new analog stick implementation. Can you add that?

**Comment by WaitingKy** [comment]
should add gamepad setup like steam link does have

**Pull request closed without merging**
