### PR TITLE
Add 1600p(16:10) Resolution Support

### PR DESCRIPTION
**Pull request by RyensX**
Add support for at least one resolution that does not distort the 16:10 screen.

### CODE REVIEW

**Comment by cgutman** [comment]
Can you describe more about your use case?

The main reason that we don't expose 16:10 resolutions by default is that GeForce Experience doesn't natively support them. When it gets instructed to start a game in an unsupported resolution (anything not 720p, 1080p, or 4K), GFE will set the display to 720p, which can be pretty confusing for the user. The native resolution option somewhat avoids this by displaying a dialog that explains all the nuances of dealing with custom resolutions.

**Comment by RyensX** [comment]
> Can you describe more about your use case?
> 
> The main reason that we don't expose 16:10 resolutions by default is that GeForce Experience doesn't natively support them. When it gets instructed to start a game in an unsupported resolution (anything not 720p, 1080p, or 4K), GFE will set the display to 720p, which can be pretty confusing for the user. The native resolution option somewhat avoids this by displaying a dialog that explains all the nuances of dealing with custom resolutions.

Although GeForce Experience does not support this resolution, this allows the 16:10 resolution to be displayed on the screen at a normal ratio (1.6), whereas all other optional resolutions (1.77) cause stretching errors

before:
raw

Moonlight


after:

**Comment by cgutman** [comment]
So your use case is:
- Your PC uses a 16:10 monitor
- Your phone doesn't have a 16:10 display (preventing native resolution options from doing what you want)
- You stream the desktop directly (avoiding the 720p issue I mentioned)

Is that correct?

**Comment by RyensX** [comment]
> So your use case is:
> 
> * Your PC uses a 16:10 monitor
> * Your phone doesn't have a 16:10 display (preventing native resolution options from doing what you want)
> * You stream the desktop directly (avoiding the 720p issue I mentioned)
> 
> Is that correct?

Yes, but I don't have direct desktop transfer.
I think adding 1600p support would provide an option for people in my situation (especially now that many laptops are using 16:10 screens) without having to go and modify the source code.

**Comment by RyensX** [comment]
> So your use case is:
> 
> * Your PC uses a 16:10 monitor
> * Your phone doesn't have a 16:10 display (preventing native resolution options from doing what you want)
> * You stream the desktop directly (avoiding the 720p issue I mentioned)
> 
> Is that correct?

Yes, but I don't have direct desktop transfer.
I think adding 1600p support would provide an option for people in my situation (especially now that many laptops are using 16:10 screens) without having to go and modify the source code.

**Comment by cgutman** [comment]
Thanks for the clarification.

I think I will implement a custom resolution dialog instead. That will allow arbitrary resolutions and give us the opportunity to let users know the limitations of custom resolutions (like we do with native resolution today).

**Comment by RyensX** [comment]
> Thanks for the clarification.
> 
> I think I will implement a custom resolution dialog instead. That will allow arbitrary resolutions and give us the opportunity to let users know the limitations of custom resolutions (like we do with native resolution today).

Thank you for your understanding. I've noticed that a number of people have mentioned custom resolutions before but the developers haven't done anything about it, so it would be great if it could be implemented in the future.

**Comment by stadros83** [comment]
Hi there
It's an old and closed Feature Request but I can't find 

> Thanks for the clarification.
> 
> I think I will implement a custom resolution dialog instead. That will allow arbitrary resolutions and give us the opportunity to let users know the limitations of custom resolutions (like we do with native resolution today).

Hi there !
It's an old and closed Feature Request but I can't find this "custom resolution" on Android.
It appears only on iOS.
Is it normal ?

**Pull request closed without merging**
