### PR TITLE
Update French

### PR DESCRIPTION
**Pull request by bubuleur**

### CODE REVIEW

**Comment by bubuleur** [comment]
Thank you for the update but you did not put my french update with?

**Comment by cgutman** [comment]
Sorry I forgot to include it in the last update.

**Comment by cgutman** [comment]
Sorry, I missed this for v5.10.3 too :(

I will merge it now so it will go into 6.0/5.10.4

**Comment by bubuleur** [comment]
No problem thank you very much ;-)

**Pull request merged**
