### PR TITLE
Androidx86( 64), android tv-x86 compatibility

### PR DESCRIPTION
**Pull request by foxtrotdragon**
Modifies blacklist conditions for omx.google script to allow omx.google decoders for android-x86 systems

### CODE REVIEW

**Comment by cgutman** [comment]
Part of the reason these were blacklisted was because of the unusable performance from these decoders. I'd like to see cases of these decoders actually performing at a performance level that's acceptable for streaming before unblacklisting them.

**Comment by foxtrotdragon** [comment]
I cant attest to other peoples machines but on my junker hp pavilion x360 with pentium cpu, it states decode time at about 120ms (android tv x86 by tosanthony)

**Comment by cgutman** [comment]
I think my preference here is to display some warning to the user if they attempt to use one of these software decoders, but allow them to continue if they want. I don't want to have a bunch of complaints from people having terrible performance only to find out they're running Android x86 on some junk netbook.

**Comment by foxtrotdragon** [comment]
yeah i think that would be for the best, i know android x86 plans on implementing codecs soon, but as for when i have no idea

**Comment by q6245wx** [comment]
Hello, do you have a CDN acceleration program?

**Pull request closed without merging**
