### PR TITLE
Add support for 8bitdo sn30 pro xCloud

### PR DESCRIPTION
**Pull request by peerobo**
Add support for 8bitdo controller: 
https://www.8bitdo.com/sn30-pro-for-xbox-cloud-gaming-on-android/
The triggers and the select button aren't working, so I add some modifications to the code.

### CODE REVIEW

**Review by cgutman — CHANGES_REQUESTED** [review]
Can you fix the indentation of your changes to match the 4 spaces convention that the rest of the file uses?

The change looks good other than that.

**Comment by peerobo** [comment]
> Can you fix the indentation of your changes to match the 4 spaces convention that the rest of the file uses?
> 
> The change looks good other than that.

It's done.

**Review by cgutman — APPROVED** [review]

**Comment by cgutman** [comment]
@peerobo It turns out that the broken mapping is due to your device running old firmware (see #978). Updating the firmware will fix the mapping. Applying the change here will break the new firmware, so I will revert this.

**Comment by peerobo** [comment]
Thanks, after updating my controller to latest firmware, I can confirm vanilla Moonlight works as intended, no need for the remapping anymore.

**Pull request merged**
