### PR TITLE
Added support for 1440p, 2K, 4K resolutions

### PR DESCRIPTION
**Pull request by anniwang**
Added 1440p, 2K, and 4K support for various screen resolutions, as requested by #73 and #106.
Ran on LG G3 and everything runs pretty smooth.

### CODE REVIEW

**Comment by Zaine6** [comment]
Is this going to make it into the next beta moonlight build? @anniwang

**Comment by cgutman** [comment]
What version of GFE did you test 1440p streaming with?

**Comment by Zaine6** [comment]
@cgutman - Version 3.5 - Beta 5. Is it meant to work in this version?

**Comment by cgutman** [comment]
I'm talking about the GeForce Experience version. Recent versions don't let you pick resolutions other than 720p, 1080p, and 4K AFAIK.

**Comment by Zaine6** [comment]
Geforce Experience - 2.8.0.80

**Comment by Zaine6** [comment]
@cgutman - What then would be the impacts of streaming at 4K yet the content being displayed at 1440?

**Comment by cgutman** [comment]
I'm waiting on this one until 4K is out of beta in GFE.

**Comment by tartooth** [comment]
Can 1440p please be implemented into the release? Even in a beta release?

Games look like garbage on 1440p phones @ 1080p and 4k is just to much for them to handle

**Comment by FolkSong** [comment]
Is there any way to get 1440p working, maybe if we use a certain version of GFE?

**Comment by slushpuppy007** [comment]
I'm using a GTX 980 Ti on my main gaming rig, connected to a 2560x1440 monitor. on my HTPC I run a GTX 970 connected to a SAMSUNG UHD/4K TV. Both Cards support HEVC. I have two questions.

1. Will I be able to stream a game to the HTPC at 4K resilution even though my Gaming PC is connected to a 2560x1440 Monitor?
2. What codec will be used for Encoding / Decoding the GameStream ?

I love this app, already streaming silky smooth at 1080p@60fps to my Raspberry Pi Model 3 B.

**Comment by The3DLink** [comment]
1: Yes, it'll stream at whatever resolution you set it to. Also, you may have to change the resolution settings in-game as well as moonlights streaming settings.

2: Depending on what device your streaming *to* is capable and what decoders it has, I believe it's either h.264 or the better h.265 (HEVC)

**Comment by The3DLink** [comment]
Moonlight has a setting to set h.264 or enable/force h.265. Again, it depends on what encoders/decoders your devices have.

**Comment by pr030880** [comment]
Hi all,
I modified the Java Legacy version a little and added the resolution 1366x768p 60Hz and 30Hz. Works absolutely flawlessly with last GeForce Experience 2.x and of course all 3.x releases.

**Comment by Kubokoo** [comment]
Is something moving in a context of this pull or is it dead idea?

**Pull request closed without merging**
