### PR TITLE
Implement performance stats overlay

### PR DESCRIPTION
**Pull request by kevinxucs**
Copied most of the logic from moonlight-qt implementation.

Add overlay stats for (along with a toggle in settings):

* Video dimensions
* Decoder name
* Estimated host PC frame rate
* Incoming frame rate from network
* Rendering frame rate
* Frames dropped by your network connection
* Average frame time
* Average decoding time

Tested on:

* Nvidia Shield TV
* Pixel 2

Example:

Screenshot_20190708-010406

### CODE REVIEW

**Comment by thw0rted** [comment]
Very clever, I was just going to post asking about this. I've been using the one in Steam's streaming client a lot lately.  The only think there that's missing in this patch is a graph of latency history but I'm sure that would be a much bigger project.

**Comment by cgutman** [comment]
This is great, thanks. I'm going to tweak a few things based on some local testing.

**Comment by kevinxucs** [comment]
Sure, thanks for merging!

**Comment by cgutman** [comment]
How do these changes look? https://github.com/moonlight-stream/moonlight-android/commit/40a3cc2ecb8e3debdf4960e4195178829ec13cbf

They improve readability on my Pixel 2 XL where the curved display margins interfere with the overlay and add some contrast. I also decided to go without overriding the platform's default "small text" appearance.

**Comment by kevinxucs** [comment]
@cgutman Looks much better, thanks for the change!

**Pull request merged**
