### PR TITLE
Mise à jour langue française

### PR DESCRIPTION
**Pull request by bubuleur**

### CODE REVIEW

**Comment by cgutman** [comment]
There are some additional strings added for the connection testing feature. Can you translate those too?

**Comment by bubuleur** [comment]
thank you it's good i changed good day

**Comment by bubuleur** [comment]
Sorry I had not seen thank you it's good I changed

**Comment by cgutman** [comment]
`title_checkbox_disable_warnings` and `summary_checkbox_disable_warnings` are also duplicated.

**Comment by bubuleur** [comment]
Update french thank you for your remark

**Comment by cgutman** [comment]
For your translation, you will need to ensure each `'` has a `\` in front of it to build successfully. There are a few of these issues in your translation.

Additionally, I noticed that there are a mix of  `’` and `'` characters in the translations. Should those be consistent?

**Comment by bubuleur** [comment]
I changed forgiveness again for this forgetfulness

**Pull request merged**
