### PR TITLE
Add opacity settings to on-screen controls

### PR DESCRIPTION
**Pull request by gotoAndDie**
Sorry for the somewhat messy set of commits, but I've added an opacity setting for on-screen controls in the settings menu.
I've also included some rudimentary translations for on-screen controller settings.

### CODE REVIEW

**Comment by 8116453** [comment]
Hello, can you build an app for me? I want to test it.

**Comment by 8116453** [comment]
mmexport1584060058397
"LtTRT" virtual button is not in the same layer as other digital buttons

**Comment by gotoAndDie** [comment]
No, the setting simply lets you make the buttons more/less transparent for every game, all the time.

I can also confirm that by changing the layers of the left trigger to 1, it becomes possible to press the A and RT buttons at the same time. I'll make a separate pull request for it.

**Comment by 8116453** [comment]
Hello, can you build an app for me?
8116453@qq.com   Thank you！！！

**Comment by gotoAndDie** [comment]
> 
> 
> Hello, can you build an app for me?
> [8116453@qq.com](mailto:8116453@qq.com) Thank you！！！

It's not safe for me to send you an app I've built. Google and Yahoo think it's a virus. (It's not, but I don't know how to prove it.)

Are you having problems with building the app yourself? It should build properly in Android Studio.

**Comment by 8116453** [comment]
Can you send an app to my email? I am not a programmer, but a lover of moonlight. I want to experience your development function! Thank you!

**Comment by cgutman** [comment]
Thanks!

**Pull request merged**
