### PR TITLE
Update French

### PR DESCRIPTION
**Pull request by bubuleur**
It is possible to put it in your next update
thanking you
For everyone

### CODE REVIEW

**Comment by bubuleur** [comment]
Little up

**Comment by bubuleur** [comment]
I come to you it is possible to translate this window?
[url=https://zupimages.net/viewer.php?id=20/01/5dtc.jpg][img]https://zupimages.net/up/20/01/5dtc.jpg[/img][/url]

**Comment by cgutman** [comment]
yes, you can translate that window. Those strings are in arrays.xml.

**Comment by bubuleur** [comment]
Thanks to you cgutman I had not seen 
Attached file translated
Thank you so much for your app which is really great
[arrays French.zip](https://github.com/moonlight-stream/moonlight-android/files/4021754/arrays.French.zip)

**Comment by bubuleur** [comment]
Is it possible to put my new translation and the one I just changed in your next update?

**Pull request merged**
