### PR TITLE
Google VR Virtual Monitor support

### PR DESCRIPTION
**Pull request by alandao**
Hi guys,

I've added a feature to the project, making it so the video is streamed to a virtual monitor in Google VR. Me and a few other people were able to test it on Daydream devices, with controller input working and such. This is my first pull request so I don't expect it to make it through as is, but could you mention what I should edit if you guys were interested in making this an official Moonlight-Android feature?

### CODE REVIEW

**Comment by madmario1000** [comment]
That's actually a good idea for  Moonlight.
However, is it possible for the following to happen:
*Have a background out of the image (i.e. [this](https://roadtovrlive-5ea0.kxcdn.com/wp-content/uploads/2016/04/steamvr-terraria-1.jpg)) 
* See if (with help from an app on the PC) is you can use a phone as a VR headset

Thanks!

**Comment by ubergeekseven** [comment]
I really want this feature! Seriously, since it's possible, it should be added. Then again, is be willing to compile it to install for myself only too.

**Comment by tristan-k** [comment]
Any reason why this never got merged?

**Comment by cgutman** [comment]
It was completely unmergeable in the state it was PR'ed. It removed the ability to even install the app on non-Daydream capable devices, increased the minimum Android supported version without discussion, duplicated a ton of code, among other things.

**Comment by tristan-k** [comment]
@cgutman Thanks for clearing it that up.

**Comment by alandao** [comment]
> It was completely unmergeable in the state it was PR'ed. It removed the ability to even install the app on non-Daydream capable devices, increased the minimum Android supported version without discussion, duplicated a ton of code, among other things.

As the author of the PR, I agree with everything mentioned here. I completely hacked this feature together with limited knowledge of Moonlight as well as Android development back when I was in school. It would have been a lot of effort to untangle this PR and get it in.

**Pull request closed without merging**
